name: Update Hoa Dao TV M3U

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Đã nâng cấp từ v3 lên v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Đã nâng cấp từ v4 lên v5
        with:
          python-version: '3.11' # Dùng bản Python mới hơn cho ổn định

      - name: Install Libs
        run: pip install requests beautifulsoup4

      - name: Run Script
        run: python hoadao_crawler.py

      - name: Push to Github
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Auto Bot"
          git add watchfrhd.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update $(date)" && git push)
